### ISSUE TITLE
The use of unit code in data model

### ISSUE THREAD

**Issue by Thue77** [smart-data-models/dataModel.GreenEnergy#5]
I do not understand the use of unit codes in the NGSI-LD format across the different models. Taking the Model PhotovoltaicDevice as an example. It has a property called "NominalPower" with the [description](https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.GreenEnergy/PhotovoltaicDevice/swagger.yaml) _Nominal Power for the panel. This is the same value of items [Pmax] for [moduleSTC] attribute. The unit code (text) is given using the [UN/CEFACT Common Codes](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes). For instance, WTT represents Watt_. 

The description says to give the unit code, but where is it given? From the example below, I only see the number 270, but no unit code to indicate what the units are?
https://github.com/smart-data-models/dataModel.GreenEnergy/blob/876bc4c0d9308724ac03ca02c7b628d3f945ee01/PhotovoltaicDevice/examples/example-normalized.jsonld#L158-L161

**Comment by bobeal** [comment]
> I do not understand the use of unit codes in the NGSI-LD format across the different models. Taking the Model PhotovoltaicDevice as an example. It has a property called "NominalPower" with the [description](https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.GreenEnergy/PhotovoltaicDevice/swagger.yaml) _Nominal Power for the panel. This is the same value of items [Pmax] for [moduleSTC] attribute. The unit code (text) is given using the [UN/CEFACT Common Codes](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes). For instance, WTT represents Watt_.
> 
> The description says to give the unit code, but where is it given? From the example below, I only see the number 270, but no unit code to indicate what the units are?
> 
> https://github.com/smart-data-models/dataModel.GreenEnergy/blob/876bc4c0d9308724ac03ca02c7b628d3f945ee01/PhotovoltaicDevice/examples/example-normalized.jsonld#L158-L161

Indeed, the example is not so good, the `NominalPower` property should be represented like this:

```
"NominalPower": {
     "type": "Property",
     "value": 270,
     "unitCode": "WTT"
}

**Comment by Thue77** [comment]
Thank you!
